server:
  port: 8888
spring:
  application:
    name: leyou-gateway

eureka:
  client:
    service-url:
      defaultZone: http://www.leyou.com:10010/eureka
    # 服务拉取间隔
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    leyou-service: /item/**